#!/bin/bash

# SGE submission options  
#$ -cwd                       	# Change to current working directory (change as needed)
#$ -V                         	# Export environment variables into script (change as needed)
#$ -S /bin/bash			# Enforce bash (don't touch!!!!)
#$ -pe smp 1			# Single CPU per qsub submission

/home/stesee/DotAligner/analysis/parametertuning/jobs/dotaligner4tuning_${SGE_TASK_ID}

